#Official DockerHub: https://hub.docker.com/r/promasu/cryptpad
version: "3.7"

services:
  cryptpad:
    container_name: cryptpad
    hostname: cryptpad
    image: promasu/cryptpad:latest
    restart: always
    environment:
      - CPAD_MAIN_DOMAIN=changethis
      - CPAD_SANDBOX_DOMAIN=changethis
    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      - ./data/config.js:/cryptpad/config/config.js
    ports:
      - '3201:3001'
      - '3202:3000'
